### ISSUE TITLE
Timeout while executing a shell script.

### ISSUE THREAD

**Issue by DeveloperRachit** [Slach/zabbix-mtr-ping#1]
when i am executing my script error is getting "Timeout while executing a shell script."
even i set Timeout 30 after that i am also getting that error

**Comment by Slach** [comment]
Please provide more details and your steps to reproduce?
which Zabbix version do you use (when I last touch this project 4.x didn't release yet)?
could you describe or attach your items configuration?
also, do you have `mtr` binary on your host where you run `zabbix-agent`?

**Comment by DeveloperRachit** [comment]
i am using zabbix 3.4 version yes i have mtr binary also

**Comment by Slach** [comment]
```
sudo -H -u zabbix /opt/zabbix-mtr-ping/zabbix-mtr.sh -n -c 3 8.8.8.8
```
works on your on host where installed zabbix-agent?

**Comment by DeveloperRachit** [comment]
yes this is working fine

**Comment by DeveloperRachit** [comment]
but when using it with conf file that is not working give me error

**Comment by Slach** [comment]
what do you mean "using it with conf file" ?
could export and paste here your zabbix mtr items in XML format?
and could you output results of following command which need run on host where installed zabbix-server
```
zabbix-get zabbix_mtr[-n -c 3 --tcp --port 443,s3.eu-west-1.amazonaws.com]
```
?

**Comment by Slach** [comment]
could you run and past here resulst on zabbix-agent host following commands?
```
cat /etc/zabbix/zabbix_agent.conf
cat /etc/zabbix/zabbix_agentd.conf.d/zabbix_mtr_ping.conf
```

**Comment by DeveloperRachit** [comment]
i have zabbix-agent

**Comment by DeveloperRachit** [comment]
cat /etc/zabbix/zabbix_agent.conf
---------------------------------------------------------
PidFile=/var/run/zabbix/zabbix_agentd.pid

LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
DebugLevel=5
Server=103.89.136.31
StartAgents=10
ServerActive=127.0.0.1
Hostname=Zabbix server
Timeout=30
Include=/etc/zabbix/zabbix_agentd.d/*.conf

**Comment by DeveloperRachit** [comment]
cat /etc/zabbix/zabbix_agentd.conf.d/zabbix_mtr_ping.conf
---------------------------------------------------------------------------------
in $1 will get ip and then this will execute
UserParameter=recaster.mtr[*],sudo -H -u zabbix /opt/zabbix-mtr-ping/zabbix_mtr.sh -n -c 3 $1

**Comment by Slach** [comment]
please look 
https://github.com/Slach/zabbix-mtr-ping/blob/master/UserParams.conf
there is expected content on zabbix_mtr_ping.conf

**Comment by DeveloperRachit** [comment]
if i would use it as like in config that would also work na
but this is not updating zabbix
UserParameter=recaster.mtr[*],sudo -H -u zabbix /opt/zabbix-mtr-ping/zabbix_mtr.sh -n -c 3 $1

**Comment by Slach** [comment]
what you mean when said, "this is not updating zabbix"? do you mean "data for items didn't update in zabbix" ?

UserParameter config which you use expect you will use only one bash parameter $1 like hostname?

could you export XML files which describe your currently used Zabbix items?
did you run zabbix-get?

**Comment by DeveloperRachit** [comment]
yes
but script executing fine but data is not updating in zabbix

**Comment by Slach** [comment]
could you export XML files which describe your currently used Zabbix items?
did you run zabbix-get?

**Comment by DeveloperRachit** [comment]
no i didn't

**Comment by Slach** [comment]
ok. please export items which you currently try used in XML format from Zabbix Server UI and attach it to this issue

**Comment by DeveloperRachit** [comment]
okay i have your files inside /opt/ and then i just created new template mtr in zabbiz GUI 
and then i given key to that recaster.mtr before that i created a dicovery that will return ip to which i have to get mtr ping
then inside conf file i did entry 
as like 
UserParameter=recaster.mtr.discovery,sudo /var/lib/zabbix/discovery.py
UserParameter=recaster.mtr[*],sudo -H -u zabbix /opt/zabbix-mtr-ping/zabbix_mtr.sh -n -c 3 $1

**Comment by Slach** [comment]
how look your recaster items in `Templates` and in `Hosts` on Zabbix server UI? could you export it via press button "export" in UI?

**Comment by DeveloperRachit** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>4.2</version>
    <date>2020-01-09T12:16:19Z</date>
    <groups>
        <group>
            <name>Cloud-Streaming/Distribution</name>
        </group>
        <group>
            <name>Recasters</name>
        </group>
    </groups>
    <hosts>
        <host>
            <host>Recaster_Apnic_NOC</host>
            <name>H1-Recaster_Apnic_NOC#R3@NOD</name>
            <description/>
            <proxy/>
            <status>0</status>
            <ipmi_authtype>-1</ipmi_authtype>
            <ipmi_privilege>2</ipmi_privilege>
            <ipmi_username/>
            <ipmi_password/>
            <tls_connect>1</tls_connect>
            <tls_accept>1</tls_accept>
            <tls_issuer/>
            <tls_subject/>
            <tls_psk_identity/>
            <tls_psk/>
            <templates>
                <template>
                    <name>Recaster Stats</name>
                </template>
                <template>
                    <name>Template OS Linux</name>
                </template>
            </templates>
            <groups>
                <group>
                    <name>Cloud-Streaming/Distribution</name>
                </group>
                <group>
                    <name>Recasters</name>
                </group>
            </groups>
            <interfaces>
                <interface>
                    <default>1</default>
                    <type>1</type>
                    <useip>1</useip>
                    <ip>103.89.136.9</ip>
                    <dns/>
                    <port>10050</port>
                    <bulk>1</bulk>
                    <interface_ref>if1</interface_ref>
                </interface>
            </interfaces>
            <applications/>
            <items/>
            <discovery_rules/>
            <httptests/>
            <macros/>
            <inventory>
                <inventory_mode>1</inventory_mode>
                <type/>
                <type_full/>
                <name>Recaster_Apnic_NOC</name>
                <alias/>
                <os>Linux Recaster_Apnic_NOC 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22</os>
                <os_full/>
                <os_short/>
                <serialno_a/>
                <serialno_b/>
                <tag/>
                <asset_tag/>
                <macaddress_a/>
                <macaddress_b/>
                <hardware/>
                <hardware_full/>
                <software/>
                <software_full/>
                <software_app_a/>
                <software_app_b/>
                <software_app_c/>
                <software_app_d/>
                <software_app_e/>
                <contact/>
                <location/>
                <location_lat/>
                <location_lon/>
                <notes/>
                <chassis/>
                <model/>
                <hw_arch/>
                <vendor/>
                <contract_number/>
                <installer_name/>
                <deployment_status/>
                <url_a/>
                <url_b/>
                <url_c/>
                <host_networks/>
                <host_netmask/>
                <host_router/>
                <oob_ip/>
                <oob_netmask/>
                <oob_router/>
                <date_hw_purchase/>
                <date_hw_install/>
                <date_hw_expiry/>
                <date_hw_decomm/>
                <site_address_a/>
                <site_address_b/>
                <site_address_c/>
                <site_city/>
                <site_state/>
                <site_country/>
                <site_zip/>
                <site_rack/>
                <site_notes/>
                <poc_1_name/>
                <poc_1_email/>
                <poc_1_phone_a/>
                <poc_1_phone_b/>
                <poc_1_cell/>
                <poc_1_screen/>
                <poc_1_notes/>
                <poc_2_name/>
                <poc_2_email/>
                <poc_2_phone_a/>
                <poc_2_phone_b/>
                <poc_2_cell/>
                <poc_2_screen/>
                <poc_2_notes/>
            </inventory>
            <tags/>
        </host>
    </hosts>
</zabbix_export>

**Comment by DeveloperRachit** [comment]
now it's time limit exceeding

**Comment by Slach** [comment]
this comment https://github.com/Slach/zabbix-mtr-ping/issues/1#issuecomment-572536211
doesn't contains anything look like `recaster.mtr`
could you attach XML file as is use GitHub attachment form look like 
![image](https://user-images.githubusercontent.com/105560/72067610-fa460500-3304-11ea-8ead-4be5b4eb21be.png)

**Comment by Slach** [comment]
close after inactivity
